# Generated by Django 4.2.7 on 2024-01-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcomApp', '0005_order_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
